name: 'update-file'
description: 'Update a file through the github api'
inputs:
  token:
    description: 'Token to authenticate with'
    required: true
  file:
    description: 'File to update'
    required: true
  committer_name:
    description: 'Name of the committer'
    required: true
  committer_email:
    description: 'Email of the committer'
    required: true
  message:
    description: 'The commit message'
    required: true
  branch:
    description: 'The name of the branch'
    required: false
    default : ''
outputs:
  sha:
    description: 'Sha of the updated file'
runs:
  using: 'node12'
  main: 'index.js'